{% set name = "apache-airflow-providers-sendgrid" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-sendgrid-{{ version }}.tar.gz
  sha256: 80593d11e89b08b500b5cc98b4d7df945c807cb37d4655d92e948dfb7942139e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.2.0
    - pip
  run:
    - python >=3.7
    - apache-airflow >=2.4.0
    - sendgrid >=6.0.0

test:
  imports:
    - airflow.providers.sendgrid
    - airflow.providers.sendgrid.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-sendgrid package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
