{% set name = "apache-airflow-providers-sendgrid" %}
{% set version = "4.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_sendgrid-{{ version }}.tar.gz
  sha256: 9214934de3b7545fe2e7614153b085860ae36f508e7d514dbb9825f25159fc4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    # no way to stay noarch: python and satisfy requirements.  Using python <3.12 for now.
    - sendgrid >=6.12.3
test:
  imports:
    - airflow.providers.sendgrid
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-sendgrid for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/sendgrid/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
