{% set name = "apache-airflow-providers-sendgrid" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-sendgrid-{{ version }}.tar.gz
  sha256: 27693d340653044b25ca5ddf521113e070eb6920a3cafb4329d20aff1af0289d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - sendgrid >=6.0.0

test:
  imports:
    - airflow.providers.sendgrid
    - airflow.providers.sendgrid.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Sendgrid for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
